version: '3.8'

services:
  eureka:
    build: ./EUREKA_SERVICE
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  customer-service:
    build: ./CUSTOMER_SERVICE
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  api-gateway:
    build: ./API_GATEWAY
    depends_on:
      - eureka
      - customer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8000:8000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
