spring:
  cloud:
    gateway:
      routes:
        - id: customer_service_staging
          uri: http://localhost:8082
          predicates:
            - Path=/customer/**
        - id: product_service_staging
          uri: http://localhost:8081
          predicates:
            - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/